# Generated by Django 5.0.3 on 2024-05-29 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noncrop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noncrop',
            name='noncrop_vaccination',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
