# Generated by Django 5.0.3 on 2024-05-29 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noncrop', '0002_alter_noncrop_noncrop_vaccination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noncrop',
            name='noncrop_hypothecated',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
