# Generated by Django 5.0.3 on 2024-05-29 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noncrop', '0003_alter_noncrop_noncrop_hypothecated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noncrop',
            name='noncrop_animalcolor',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
