# Generated by Django 5.0.3 on 2024-05-30 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='personaldetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state1', models.CharField(max_length=100)),
                ('product1', models.CharField(max_length=100)),
                ('config', models.CharField(blank=True, max_length=100, null=True)),
                ('aadhar', models.CharField(max_length=12)),
                ('farmerName1', models.CharField(max_length=100)),
                ('guardian', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('number1', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=10)),
                ('caste', models.CharField(max_length=100)),
                ('resState1', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('block1', models.CharField(max_length=100)),
                ('grampanch', models.CharField(max_length=100)),
                ('village', models.CharField(max_length=100)),
                ('h_no', models.CharField(max_length=100)),
                ('pin', models.CharField(max_length=6)),
                ('category1', models.CharField(max_length=100)),
                ('nature1', models.CharField(max_length=100)),
                ('mandi', models.CharField(blank=True, max_length=100, null=True)),
                ('invoice', models.CharField(blank=True, max_length=100, null=True)),
                ('retailstore1', models.CharField(blank=True, max_length=100, null=True)),
                ('bankname', models.CharField(max_length=100)),
                ('branchname', models.CharField(max_length=100)),
                ('ifsc1', models.CharField(max_length=11)),
                ('account_no', models.CharField(max_length=18)),
                ('nominee_name', models.CharField(max_length=100)),
                ('nominee_relation', models.CharField(max_length=100)),
                ('nominee_age', models.PositiveIntegerField()),
            ],
        ),
    ]
