# Generated by Django 5.0.3 on 2024-05-20 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='homepage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homepage_username', models.CharField(max_length=50)),
                ('homepage_password', models.CharField(max_length=50)),
            ],
        ),
    ]
